dist: bionic

language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
    - eval "${MATRIX_EVAL}"

jobs:
  include:
    - stage: Build
      script: ./.travis/build.sh
    - stage: Format
      script: ./.travis/format.sh
